version: "3.9"
services:
  api:
    build: .
    environment:
      - APP_ENV=development
      - LOG_LEVEL=INFO
      - API_KEYS=dev-key-123
    ports:
      - "8000:8000"
  ui:
    image: python:3.12-slim
    working_dir: /app
    environment:
      - API_URL=http://api:8000
      - API_KEY=dev-key-123
    volumes:
      - ./ui:/app
      - ./pyproject.toml:/app/pyproject.toml:ro
    command: bash -lc "pip install -U pip && pip install .[ui] && streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=8501"
    ports:
      - "8501:8501"
    depends_on:
      - api